[theme]
primaryColor = "#1f77b4"  # Cor primária (azul padrão do Streamlit)
backgroundColor = "#ffffff"  # Cor de fundo (branco)
secondaryBackgroundColor = "#f0f2f6"  # Cor de fundo secundária
textColor = "#000000"  # Cor do texto (preto)
font = "sans serif"  # Tipo de fonte
