[theme]
primaryColor = "#1f77b4"  # Azul padrão
backgroundColor = "#ffffff"  # Branco
secondaryBackgroundColor = "#f0f2f6"  # Cinza claro
textColor = "#000000"  # Preto
font = "sans serif"  # Fonte padrão
